version: '3.8'

services:
  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"
    networks:
      - banky-net

  gateway-service:
    build: ./gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service
    networks:
      - banky-net

  customer-service:
    build: ./customer-service
    ports:
      - "8081:8081"
    depends_on:
      - discovery-service
    networks:
      - banky-net

networks:
  banky-net:
    driver: bridge
