services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bankydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - banky-net

  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"
    networks:
      - banky-net

  gateway-service:
    build: ./gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service
    networks:
      - banky-net

  customer-service:
    build: ./customer-service
    ports:
      - "8081:8081"
    depends_on:
      - discovery-service
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bankydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    command: [ "java", "-jar", "app.jar" ]
    restart: on-failure
    networks:
      - banky-net

  account-service:
    build: ./account-service
    ports:
      - "8082:8082"
    depends_on:
      - discovery-service
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bankydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    command: [ "java", "-jar", "app.jar" ]
    restart: on-failure
    networks:
      - banky-net

networks:
  banky-net:
    driver: bridge
volumes:
  pgdata: