spring:
  application:
    name: gateway-service

server:
  port: 8080

  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/customers/**
          filters:
            - StripPrefix=2

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka